### PR TITLE
Fix broken gcfg import and run gofmt on all .go files

### PR DESCRIPTION
**Pull request by rameshg87**

### CODE REVIEW

**Comment by sci4me** [comment]
The travis build fails?

**Comment by rameshg87** [comment]
I have changed the import path of "gocfg" from "code.google.com/p/gcfg" to "gopkg.in/gcfg.v1". But still it tries to go get the old import path.

```
$ go get code.google.com/p/gcfg
package code.google.com/p/gcfg: unable to detect version control system for code.google.com/ path
```

Any idea why it could be so ?

**Comment by sci4me** [comment]
Well did you change it in the Travis yml file?

**Comment by rameshg87** [comment]
Ah, I missed that. I grepped for anywhere else it being used, but couldn't see it because it is a hidden file. Updated that now and travis is happy.

**Comment by sci4me** [comment]
Good stuff. Thanks!

**Pull request merged**
